# -*- coding: utf-8 -*-
"""Sachin_EDA.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1m-2irtoZSKgGTY9MB6LfVWCozs8ffKrX
"""

# Commented out IPython magic to ensure Python compatibility.
# %pip install pandas numpy matplotlib seaborn

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import os
pd.set_option('display.max_columns', None)
pd.set_option('display.width', 1000)

"""EDA For Stores_sales_hader table"""

import pandas as pd

# read data
sales = pd.read_csv("store_sales_header.csv")

# 1. missing values
print("\nMissing values per column:")
print(sales.isna().sum())

# 2. duplicate transactions
print("\nDuplicate rows:", sales.duplicated().sum())

# 3. missing total_amount
print("\nMissing total_amount:",
      sales["total_amount"].isna().sum())

# 4. zero or negative total_amount
print("Zero or negative total_amount:",
      (sales["total_amount"] <= 0).sum())

# 5. invalid transaction dates
bad_dates = pd.to_datetime(
    sales["transaction_date"], errors="coerce"
).isna().sum()
print("Invalid transaction_date:", bad_dates)

# 6. quick stats for sanity check
print("\nTotal amount summary:")
print(sales["total_amount"].describe())

"""EDA for Store_sales_line_items

"""

import pandas as pd

lines = pd.read_csv("store_sales_line_items.csv")

print("Sales line items check\n")

print("Rows and columns:", lines.shape)

print("\nMissing values:")
print(lines.isna().sum())

print("\nDuplicate rows:", lines.duplicated().sum())
print("Duplicate line_item_id:", lines["line_item_id"].duplicated().sum())

print("\nQuantity issues:", (lines["quantity"] <= 0).sum())

print("Missing line_item_amount:",
      lines["line_item_amount"].isna().sum())

print("Line_item_amount issues:",
      (lines["line_item_amount"] <= 0).sum())

print("\nQuantity summary:")
print(lines["quantity"].describe())

print("\nLine item amount summary:")
print(lines["line_item_amount"].describe())

import pandas as pd

lines = pd.read_csv("store_sales_line_items.csv")

print("Sales line items EDA\n")

print("Rows and columns:", lines.shape)

print("\nMissing values:")
print(lines.isna().sum())

print("\nDuplicate rows:", lines.duplicated().sum())

print("\nQuantity issues:", (lines["quantity"] <= 0).sum())
print("Missing line_item_amount:", lines["line_item_amount"].isna().sum())
print("Line_item_amount issues:", (lines["line_item_amount"] <= 0).sum())

# -----------------------
# simple cleaning
# -----------------------

clean_lines = lines.copy()

# fix quantity problems
clean_lines.loc[clean_lines["quantity"] <= 0, "quantity"] = 1

# fix missing or bad amounts
clean_lines["line_item_amount"] = clean_lines["line_item_amount"].fillna(0)
clean_lines.loc[
    clean_lines["line_item_amount"] < 0, "line_item_amount"
] = 0

# promotion_id can be empty (not all items are promoted)
clean_lines["promotion_id"] = clean_lines["promotion_id"].fillna("NO_PROMO")

print("\nAfter cleaning\n")
print("Missing values:")
print(clean_lines.isna().sum())

print("\nQuantity summary:")
print(clean_lines["quantity"].describe())

print("\nLine item amount summary:")
print(clean_lines["line_item_amount"].describe())

# save cleaned data
clean_lines.to_csv("store_sales_line_items_cleaned.csv", index=False)

print("\nCleaned file saved as store_sales_line_items_cleaned.csv")